"""
Hardware Specification Parser (Markdown → Structured JSON)
==========================================================

Extracts hardware register specifications from a Markdown file that was
previously generated by ``pdf_parser.py`` from a hardware-manual PDF.

All extraction is **regex-based** — no LLM calls.  The parser is fully
dynamic and module-agnostic (works with CXPI, SPI, I2C, ADC, etc.).

**5 entity types extracted:**

1. Registers — name, offset address, reset value
2. Fields — bit-field definitions (name, bits, type, description)
3. Interrupts — single-bit fields in interrupt registers
4. Errors — fields containing ERROR / FAULT / TIMEOUT keywords
5. Formulas — real calculation formulas (baud rate, clock dividers, etc.)

**6 relationship types built:**

1. ``register_has_field`` — register → field
2. ``error_sets_interrupt`` — error field → interrupt flag
3. ``field_used_in_formula`` — field ↔ formula
4. ``field_enables_feature`` — field → HW feature
5. ``interrupt_masked_by_field`` — (stub, future)
6. ``operation_triggers_interrupt`` — operation → interrupt

Usage::

    from IngestionPipeline.Parsers import hw_spec_parser

    result = hw_spec_parser.parse("cxpi_hw_manual.md")
    # result is a dict with registers, fields, interrupts, errors,
    # formulas, relationships, and metadata.
"""

from __future__ import annotations

import logging
import re
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Keyword sets
# ---------------------------------------------------------------------------
_INTERRUPT_KWS = {"INTR", "INT", "IRQ", "INTERRUPT"}

_ERROR_KWS = {
    "ERROR", "ERR", "FAULT", "TIMEOUT", "FAIL",
    "VIOLATION", "LOSS", "ARB_LOST", "OVERRUN", "UNDERRUN",
}

_ENABLE_KWS = [
    "enable", "enabled", "disable", "disabled",
    "activation", "activate", "deactivate",
    "must be set", "should be set", "control",
    "turn on", "turn off", "switch on", "switch off",
]

_OP_KWS: Dict[str, str] = {
    "transmit": "transmit", "transmission": "transmit",
    "send": "send", "sending": "send",
    "receive": "receive", "reception": "receive", "receiving": "receive",
    "transfer": "transfer", "read": "read", "write": "write",
    "enable": "enable", "disable": "disable",
    "reset": "reset", "initialize": "init", "configuration": "config",
}

_TIMING_KWS = ["after", "when", "on", "upon", "during", "at", "before", "following"]
_STATUS_WORDS = {"done", "error", "complete", "ready", "flag", "status"}


# ---------------------------------------------------------------------------
# Internal extractor
# ---------------------------------------------------------------------------

class _HWSpecExtractor:
    """Regex-based hardware specification extractor."""

    def __init__(self, content: str, source_name: str):
        self._content = content
        self._lines = content.split("\n")
        self._source = source_name

    # ── helpers ──────────────────────────────────────────────────────

    @staticmethod
    def _is_formatting_row(cells: List[str]) -> bool:
        for cell in cells:
            c = cell.strip()
            if not c:
                continue
            if re.match(r"^[:\-\s]+$", c):
                return True
        first = cells[0].strip().lower() if cells else ""
        return first in {"field", "name", "bit", "bits"}

    @staticmethod
    def _is_reserved(name: str) -> bool:
        c = name.strip()
        return c == "0" or c.lower() == "reserved"

    # ── 1. Registers ────────────────────────────────────────────────

    def extract_registers(self) -> List[Dict[str, Any]]:
        registers: List[Dict[str, Any]] = []
        seen: set[str] = set()
        pat1 = re.compile(r"^([A-Z][A-Za-z0-9_]+(?:\s*\([^)]+\))?)\s*[–—]\s*(.+)$")

        i = 0
        while i < len(self._lines):
            line = self._lines[i].strip()

            # Pattern 1: NAME — Description (same line)
            m = pat1.match(line)
            if m:
                short = re.sub(r"\s*\([^)]+\)", "", m.group(1)).strip()
                if short not in seen:
                    reg = self._scan_offset_reset(i, short, m.group(2).strip())
                    if reg:
                        seen.add(short)
                        registers.append(reg)
                i += 1
                continue

            # Pattern 2: NAME alone on a line, description on next line(s)
            if (
                re.match(r"^[A-Z][A-Za-z0-9_]+(?:\s*\([^)]+\))?\s*$", line)
                and len(line) <= 50
            ):
                short = re.sub(r"\s*\([^)]+\)", "", line).strip()
                if ("_" in short or short.isupper()) and short not in seen:
                    long_name = self._find_description(i)
                    if long_name:
                        reg = self._scan_offset_reset(i, short, long_name, lookahead=11)
                        if reg:
                            seen.add(short)
                            registers.append(reg)
            i += 1

        logger.info("Extracted %d registers", len(registers))
        return registers

    def _scan_offset_reset(
        self, start: int, short: str, long_name: str, lookahead: int = 6
    ) -> Dict[str, Any] | None:
        offset = reset_value = reset_type = None
        for j in range(start + 1, min(start + lookahead, len(self._lines))):
            ahead = self._lines[j].strip()
            if ahead.startswith("- "):
                ahead = ahead[2:].strip()
            if ahead.startswith("Offset address:"):
                offset = ahead.replace("Offset address:", "").strip()
            rm = re.match(r"(rst_\w+)\s+value:\s*(.+)", ahead)
            if rm:
                reset_type, reset_value = rm.group(1), rm.group(2).strip()
        if not offset:
            return None
        return {
            "name": short,
            "long_name": long_name,
            "offset": offset,
            "reset_value": reset_value,
            "reset_type": reset_type,
        }

    def _find_description(self, start: int) -> str | None:
        for idx in range(start + 1, min(start + 15, len(self._lines))):
            cl = self._lines[idx].strip()
            if not cl:
                continue
            raw = cl[2:].strip() if cl.startswith("- ") else cl
            if raw.startswith("Offset") or re.match(r"^rst_\w+", raw) or raw.startswith("|"):
                continue
            if re.match(r"^[A-Z][A-Za-z0-9_]+(?:\s*\([^)]+\))?\s*$", cl) and len(cl) <= 50:
                break
            if len(cl) > 10:
                return cl
        return None

    # ── 2. Fields ───────────────────────────────────────────────────

    def extract_fields(self, registers: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        reg_info = [
            {"name": r["name"], "long_name": r["long_name"]}
            for r in registers
        ]

        all_fields: List[Dict[str, Any]] = []
        i = 0
        while i < len(self._lines):
            line = self._lines[i]
            current_reg = self._match_register_context(line, i, reg_info)
            if current_reg:
                for j in range(i, min(i + 100, len(self._lines))):
                    tl = self._lines[j]
                    if tl.strip().startswith("|") and tl.count("|") >= 4:
                        field = self._parse_field_row(tl, current_reg)
                        if field:
                            all_fields.append(field)
            i += 1

        # Deduplicate
        seen: set[tuple] = set()
        unique: List[Dict[str, Any]] = []
        for f in all_fields:
            key = (f["parent_register"], f["name"], f["bits"])
            if key not in seen:
                seen.add(key)
                unique.append(f)

        logger.info("Extracted %d unique fields", len(unique))
        return unique

    def _match_register_context(
        self, line: str, idx: int, reg_info: List[Dict]
    ) -> str | None:
        for ri in reg_info:
            if ri["name"] in line or ri["long_name"] in line:
                if "\u2014" in line or "\u2013" in line:
                    return ri["name"]
                for ci in range(idx + 1, min(idx + 5, len(self._lines))):
                    if "offset address" in self._lines[ci].lower():
                        return ri["name"]
        return None

    def _parse_field_row(self, line: str, register: str) -> Dict[str, Any] | None:
        cells = [c.strip() for c in line.split("|")[1:-1]]
        if len(cells) < 3 or self._is_formatting_row(cells):
            return None
        name = cells[0].strip()
        bits = cells[1].strip() if len(cells) > 1 else ""
        ftype = cells[2].strip() if len(cells) > 2 else ""
        desc = cells[3].strip() if len(cells) > 3 else ""
        if self._is_reserved(name) or not name or not bits:
            return None
        if not re.match(r"^\d+(:\d+)?$", bits):
            return None
        if ftype and not re.match(r"^r[wh]?|w$", ftype):
            return None
        return {
            "name": name,
            "parent_register": register,
            "bits": bits,
            "type": ftype,
            "description": desc[:200],
        }

    # ── 3. Interrupts ──────────────────────────────────────────────

    def extract_interrupts(self) -> List[Dict[str, Any]]:
        sections = []
        for i, line in enumerate(self._lines):
            if "\u2014" not in line:
                continue
            parts = line.split("\u2014")
            if len(parts) < 2:
                continue
            reg_name = re.sub(r"\s*\([^)]+\)", "", parts[0].strip()).strip()
            desc = parts[1].strip().lower()
            if any(kw in reg_name.upper() for kw in _INTERRUPT_KWS) or "interrupt" in desc:
                sections.append({"register": reg_name, "line": i})

        interrupts: List[Dict[str, Any]] = []
        for sec in sections:
            for j in range(sec["line"], min(sec["line"] + 150, len(self._lines))):
                tl = self._lines[j]
                if not (tl.strip().startswith("|") and tl.count("|") >= 4):
                    continue
                cells = [c.strip() for c in tl.split("|")[1:-1]]
                if len(cells) < 3 or self._is_formatting_row(cells):
                    continue
                name = cells[0].strip()
                bits = cells[1].strip() if len(cells) > 1 else ""
                desc = cells[3].strip() if len(cells) > 3 else ""
                if self._is_reserved(name) or not name or not bits:
                    continue
                if not re.match(r"^\d+$", bits):
                    continue
                interrupts.append({
                    "name": name,
                    "register": sec["register"],
                    "bit": int(bits),
                    "description": desc[:200],
                })

        logger.info("Extracted %d interrupts", len(interrupts))
        return interrupts

    # ── 4. Errors ───────────────────────────────────────────────────

    def extract_errors(self) -> List[Dict[str, Any]]:
        errors: List[Dict[str, Any]] = []
        seen: set[str] = set()
        current_reg: str | None = None

        for line in self._lines:
            if "\u2014" in line and not line.strip().startswith("|"):
                m = re.match(r"^([A-Z][A-Za-z0-9_]+)", line.split("\u2014")[0].strip())
                if m:
                    current_reg = m.group(1)

            if not current_reg or not (line.strip().startswith("|") and line.count("|") >= 4):
                continue
            cells = [c.strip() for c in line.split("|")[1:-1]]
            if len(cells) < 3 or self._is_formatting_row(cells):
                continue
            name = cells[0].strip()
            bits = cells[1].strip() if len(cells) > 1 else ""
            desc = cells[3].strip() if len(cells) > 3 else ""
            if not any(kw in name.upper() for kw in _ERROR_KWS):
                continue
            if not re.match(r"^\d+(:\d+)?$", bits) or name in seen:
                continue
            seen.add(name)

            upper = name.upper()
            if "TX" in upper or "TRANSMIT" in upper or "SEND" in upper:
                etype = "transmission"
            elif "RX" in upper or "RECEIVE" in upper or "RECV" in upper:
                etype = "reception"
            elif "BUS" in upper or "ARB" in upper:
                etype = "bus"
            elif "PARITY" in upper or "CRC" in upper or "CHECKSUM" in upper:
                etype = "data_integrity"
            elif "TIMEOUT" in upper or "WATCHDOG" in upper:
                etype = "timing"
            else:
                etype = "general"

            errors.append({
                "name": name,
                "type": etype,
                "description": desc[:200],
                "detected_in": current_reg,
                "bit": int(bits.split(":")[0]) if re.match(r"^\d+", bits) else None,
            })

        logger.info("Extracted %d errors", len(errors))
        return errors

    # ── 5. Formulas ─────────────────────────────────────────────────

    def extract_formulas(self) -> List[Dict[str, Any]]:
        formulas: List[Dict[str, Any]] = []
        seen: set[str] = set()

        def _add(text: str) -> None:
            text = text.strip()
            if text in seen:
                return
            if re.match(r"^[A-Z_]+\s*=\s*\d+$", text):
                return
            if text.endswith("= (") or text.endswith("=("):
                return
            seen.add(text)
            formulas.append({
                "name": f"formula_{len(formulas) + 1}",
                "formula": text,
                "type": "calculation",
                "description": "Mathematical formula from hardware manual",
            })

        # Method 1: LaTeX $$...$$ blocks
        for m in re.finditer(r"\$\$(.+?)\$\$", self._content, re.DOTALL):
            _add(m.group(1))

        # Method 2: plain-text equations with math operators
        eq_pat = re.compile(
            r"^[\s\-•]*([A-Za-z_][A-Za-z0-9_,\.]*)\s*=\s*(.+?)(?:\s*\[Equation\s+\d+\])?$"
        )
        for line in self._lines:
            m = eq_pat.match(line.strip())
            if m:
                expr = m.group(2).strip()
                if any(op in expr for op in ["/", "*", "+", "-", "\u00d7", "\u00f7", "(", ")"]):
                    if not re.match(r"^\d+(\.\d+)?$", expr):
                        _add(f"{m.group(1)} = {expr}")

        # Method 3: labeled equations [Equation N]
        lbl = re.compile(r"\[Equation\s+\d+\]")
        for line in self._lines:
            if lbl.search(line):
                part = lbl.split(line)[0].strip()
                if part and "=" in part:
                    part = re.sub(r"^[\s\-•]+", "", part)
                    _add(part)

        logger.info("Extracted %d formulas", len(formulas))
        return formulas

    # ── 6. Relationships ────────────────────────────────────────────

    def build_relationships(
        self,
        registers: List[Dict],
        fields: List[Dict],
        interrupts: List[Dict],
        errors: List[Dict],
        formulas: List[Dict],
    ) -> Dict[str, List[Dict]]:
        rels: Dict[str, List[Dict]] = {
            "register_has_field": [],
            "error_sets_interrupt": [],
            "field_used_in_formula": [],
            "field_enables_feature": [],
            "interrupt_masked_by_field": [],
            "operation_triggers_interrupt": [],
        }

        # 1. register_has_field
        for f in fields:
            rels["register_has_field"].append({
                "register": f["parent_register"],
                "field": f["name"],
                "bits": f["bits"],
            })

        # 2. error_sets_interrupt
        seen_ei: set[tuple] = set()
        for err in errors:
            for intr in interrupts:
                if intr["name"] == err["name"]:
                    key = (err["name"], intr["name"], intr["register"], intr["bit"])
                    if key not in seen_ei:
                        seen_ei.add(key)
                        rels["error_sets_interrupt"].append({
                            "error": err["name"],
                            "error_register": err["detected_in"],
                            "interrupt": f"{intr['register']}.{intr['name']}",
                            "interrupt_register": intr["register"],
                            "interrupt_bit": intr["bit"],
                        })

        # 3. field_used_in_formula
        rels["field_used_in_formula"] = self._field_formula_rels(fields, formulas)

        # 4. field_enables_feature
        rels["field_enables_feature"] = self._field_enables_rels(fields)

        # 5. interrupt_masked_by_field (stub)
        # Will be implemented when mask-register patterns are finalised.

        # 6. operation_triggers_interrupt
        rels["operation_triggers_interrupt"] = self._op_trigger_rels(interrupts)

        for k, v in rels.items():
            logger.info("  %s: %d", k, len(v))
        return rels

    # ── relationship helpers ─────────────────────────────────────────

    def _field_formula_rels(
        self, fields: List[Dict], formulas: List[Dict]
    ) -> List[Dict]:
        lookup: Dict[str, Dict] = {}
        for f in fields:
            lookup[f["name"]] = f
            lookup[f["name"].replace("_", "")] = f

        rels: List[Dict] = []
        seen: set[tuple] = set()
        for formula in formulas:
            clean = (
                formula["formula"]
                .replace("\\_", "_")
                .replace("\\times", "*")
                .replace("\\text{", "")
                .replace("\\,", " ")
                .replace("\\quad", " ")
            )
            for potential in re.findall(
                r"[A-Z][A-Za-z0-9_]*(?:\.[A-Z][A-Za-z0-9_]*)?", clean
            ):
                fname = potential.split(".")[-1] if "." in potential else potential
                if fname not in lookup:
                    continue
                fi = lookup[fname]
                role = (
                    "output"
                    if re.search(rf"^{re.escape(fname)}\s*=", clean)
                    else "input"
                )
                key = (formula["name"], fname, fi["parent_register"])
                if key not in seen:
                    seen.add(key)
                    rels.append({
                        "formula": formula["name"],
                        "field": fname,
                        "register": fi["parent_register"],
                        "bits": fi["bits"],
                        "role": role,
                        "formula_content": formula["formula"][:100],
                    })
        return rels

    def _field_enables_rels(self, fields: List[Dict]) -> List[Dict]:
        rels: List[Dict] = []
        seen: set[tuple] = set()
        for f in fields:
            desc = f.get("description", "").lower()
            if not any(kw in desc for kw in _ENABLE_KWS):
                continue
            feature = None
            m = re.search(r"enable\s+(?:the\s+)?([a-z_][a-z0-9_\s]*)", desc)
            if m:
                feature = m.group(1).strip().replace(" ", "_")
            if not feature:
                m = re.search(r"([a-z_][a-z0-9_\s]*)\s+enable", desc)
                if m:
                    feature = m.group(1).strip().replace(" ", "_")
            if not feature:
                feature = (
                    re.sub(r"(_EN|_ENABLE|_ENABLED|EN)$", "", f["name"], flags=re.I).lower()
                    + "_feature"
                )
            key = (f["name"], f["parent_register"], feature)
            if key not in seen:
                seen.add(key)
                rels.append({
                    "field": f["name"],
                    "register": f["parent_register"],
                    "bits": f["bits"],
                    "feature": feature,
                    "enable_value": 1,
                    "disable_value": 0,
                    "description": f.get("description", "")[:100],
                })
        return rels

    def _op_trigger_rels(self, interrupts: List[Dict]) -> List[Dict]:
        rels: List[Dict] = []
        seen: set[tuple] = set()
        for intr in interrupts:
            name = intr["name"]
            desc = intr.get("description", "").lower()
            operation = self._detect_operation(name, desc)
            timing = self._detect_timing(name, desc)
            if operation:
                key = (operation, name)
                if key not in seen:
                    seen.add(key)
                    rels.append({
                        "operation": operation,
                        "interrupt": name,
                        "interrupt_register": intr["register"],
                        "interrupt_bit": intr["bit"],
                        "timing": timing,
                        "description": intr.get("description", "")[:100],
                    })
        return rels

    @staticmethod
    def _detect_operation(name: str, desc: str) -> str | None:
        # From description
        for tkw in _TIMING_KWS:
            if tkw in desc:
                remaining = desc.split(tkw, 1)[1]
                for ok, on in _OP_KWS.items():
                    if ok in remaining:
                        return on
        # From interrupt name
        upper = name.upper()
        if "TX" in upper or "TRANSMIT" in upper:
            return "transmit"
        if "RX" in upper or "RECEIVE" in upper:
            return "receive"
        if "SEND" in upper:
            return "send"
        # Generic: strip status words
        parts = name.lower().split("_")
        op_parts = [p for p in parts if p not in _STATUS_WORDS]
        return "_".join(op_parts) if op_parts else None

    @staticmethod
    def _detect_timing(name: str, desc: str) -> str:
        if "after" in desc or "complete" in desc or "done" in name.lower():
            return "after_completion"
        if "before" in desc or "start" in desc:
            return "before_start"
        if "during" in desc:
            return "during_operation"
        if "error" in name.lower() or "error" in desc:
            return "on_error"
        return "on_event"

    # ── top-level ────────────────────────────────────────────────────

    def extract_all(self) -> Dict[str, Any]:
        registers = self.extract_registers()
        fields = self.extract_fields(registers)
        interrupts = self.extract_interrupts()
        errors = self.extract_errors()
        formulas = self.extract_formulas()
        relationships = self.build_relationships(
            registers, fields, interrupts, errors, formulas,
        )
        return {
            "metadata": {
                "source_file": self._source,
                "total_lines": len(self._lines),
                "extraction_date": datetime.now().isoformat(),
                "counts": {
                    "registers": len(registers),
                    "fields": len(fields),
                    "interrupts": len(interrupts),
                    "errors": len(errors),
                    "formulas": len(formulas),
                },
            },
            "registers": registers,
            "fields": fields,
            "interrupts": interrupts,
            "errors": errors,
            "formulas": formulas,
            "relationships": relationships,
        }


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def parse(path: str) -> Dict[str, Any]:
    """
    Extract hardware specifications from a Markdown file.

    The input should be a Markdown file produced by ``pdf_parser.parse()``
    from an Infineon hardware-manual PDF.

    Args:
        path: Path to the ``.md`` file.

    Returns:
        A dict with keys ``metadata``, ``registers``, ``fields``,
        ``interrupts``, ``errors``, ``formulas``, and ``relationships``.

    Raises:
        FileNotFoundError: If *path* does not exist.
    """
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"File not found: {path}")

    content = p.read_text(encoding="utf-8")
    logger.info("Parsing hardware spec from %s (%d lines)", p.name, content.count("\n") + 1)

    return _HWSpecExtractor(content, p.name).extract_all()
