/* Stub: Adc_Data.h — Includes the real Adc.h (from ssc/inc via -I paths)
   for type definitions, with stubs providing infrastructure headers.
   Does not pull in the template Adc_Cfg.h since the stub shadows it. */
#ifndef ADC_DATA_H
#define ADC_DATA_H

#include "Adc.h"
#include "SchM_Adc.h"
#include "Mcal_ExecutionContext.h"

/* Config constants normally generated by the configuration tool */
#ifndef ADC_TMADC_KERNEL_COUNT
#define ADC_TMADC_KERNEL_COUNT  12u
#endif
#ifndef ADC_CFG_PARTITION_COUNT
#define ADC_CFG_PARTITION_COUNT  4u
#endif
#ifndef ADC_SCHM_COUNT
#define ADC_SCHM_COUNT           4u
#endif
#ifndef ADC_MAX_DMA_CH_ID
#define ADC_MAX_DMA_CH_ID        15u
#endif
#ifndef RMA_TOTAL_EXEC_UNITS_AVAILABLE
#define RMA_TOTAL_EXEC_UNITS_AVAILABLE 8u
#endif
#ifndef ADC_PARTITION_ID_OFF
#define ADC_PARTITION_ID_OFF      0u
#endif
#ifndef ADC_HWUNIT_ID_OFF
#define ADC_HWUNIT_ID_OFF         8u
#endif
#ifndef ADC_GRP_ID_OFF
#define ADC_GRP_ID_OFF            16u
#endif
#ifndef ADC_RESULTHANDLINGMODE_OFF
#define ADC_RESULTHANDLINGMODE_OFF 24u
#endif
#ifndef ADC_GRP_SYMBOLIC_NAME
#define ADC_GRP_SYMBOLIC_NAME(a,b,c,d) ((uint32)(a) | ((uint32)(b) << 8u) | ((uint32)(c) << 16u) | ((uint32)(d) << 24u))
#endif

/* Extern global variables (the targets for SRC_USES_GLOBAL edges) */
extern const Adc_PartitionDataType * const Adc_kData[ADC_CFG_PARTITION_COUNT];
extern const Adc_SchMFnType Adc_kSchMFnMap[ADC_SCHM_COUNT];
extern const Adc_DmaChIdMapType Adc_kDmaChIdMap[(ADC_MAX_DMA_CH_ID + 1u)];
extern const uint8 Adc_kExecUnitToPartitionIdMap[RMA_TOTAL_EXEC_UNITS_AVAILABLE];

#endif /* ADC_DATA_H */
